In [ ]:
"""NumPy is a Python library.
NumPy is used for working with arrays.
NumPy is short for Numerical Python """

# importing numPy and NumPy Version

In [1]:
import numpy as np
n1 = np.array([19,67,54,35])
n1
type(n1)
print(np.__version__)

1.22.3


# initialization NumPy 0 value using "zeros()" method

In [17]:
n2 = np.zeros((1,2))
n2
n2 = np.zeros((5,5))
n2




array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
print(n2.ndim) # dimensions of array

2


# initialization NumPy array with same number  using "full()" method

In [33]:
n3= np.full((4,5),16)
n3

array([[16, 16, 16, 16, 16],
       [16, 16, 16, 16, 16],
       [16, 16, 16, 16, 16],
       [16, 16, 16, 16, 16]])

In [37]:
n3.shape #show the shape of array 
         
n3.shape = (5,4)   # we can change shape
n3

array([[16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16],
       [16, 16, 16, 16]])

# initialization NumPy array within a range

In [30]:
n =np.arange(10,20)
n =np.arange(10,20,2) #here 10 is initial point which was inclusive 20 is end point and 2 is skiping unit
n

array([10, 12, 14, 16, 18])

# random number 

In [31]:
n = np.random.randint(1,100,10)
n


array([92, 43, 64,  7,  4, 98, 73, 61, 52, 43])

# Slice elements 
# Slice elements with step

In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])
print(arr[1:5:2])

[2 3 4 5]
[2 4]


# Data Type of an Array

In [42]:
arr = np.array([1, 2, 3, 4])
print(arr.dtype)
arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

int32
<U6


# Iterate on the elements

In [58]:
arr = np.array([1, 2, 3])
for x in arr:
  print(x)

arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  print(x)

arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
  for y in x:
    print(y)

1
2
3
[1 2 3]
[4 5 6]
1
2
3
4
5
6


# join

In [67]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

#horizontal
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

#vertical
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

#depth
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.dstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


# Splitting Arrays

In [70]:
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
print(newarr)


arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


# Searching Arrays

In [76]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
print(x)

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
print(x)

(array([3, 5, 6], dtype=int64),)
(array([1, 3, 5, 7], dtype=int64),)


In [78]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7)
print(x)

1


In [80]:
arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print(x)

2


# sort array

In [83]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))


arr = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr))

[0 1 2 3]
[[2 3 4]
 [0 1 5]]


# intersction and Difference

In [4]:
n1 = np.array([10,20,30,40,50,60])
n2 = np.array([40,50,60,70,80,90])
np.intersect1d(n1,n2)

array([40, 50, 60])

In [7]:
np.setdiff1d(n1,n2)

array([10, 20, 30])

In [8]:
np.setdiff1d(n2,n1)

array([70, 80, 90])

# Addition

In [13]:
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])

In [15]:
np.sum([n1,n2]) #sum of all the element

210

In [17]:
np.sum([n1,n2],axis=0) #add array coulmn wise

array([50, 70, 90])

In [46]:
#without using function

n1 = np.array([10,20,30])
n2 = np.array([40,50,60])
z=[]
for i,j in zip(n1,n2):
    z.append(i+j)
print(z)

[50, 70, 90]


In [18]:
np.sum([n1,n2],axis=1) #add array row wise


array([ 60, 150])

# Basic Math function

In [32]:
n1 = np.array([10,20,30])
n2 = np.array([40,50,60])
n1=n1+1
n1

array([11, 21, 31])

In [33]:
n1=n1*2
n1

array([22, 42, 62])

In [34]:
n1=n1-1
n1

array([21, 41, 61])

In [35]:
n1=n1/2
n1

array([10.5, 20.5, 30.5])

In [36]:
np.mean(n2) 

50.0

In [37]:
np.std(n2)

8.16496580927726

In [38]:
np.median(n2)

50.0

In [47]:
x= np.lcm(n1,n2)
x

array([ 40, 100,  60])

# saveing and loading array

In [41]:
n1 = np.array([10,20,30,40,50,60])
np.save('final_array',n1)
n2 =np.load('final_array.npy')
n2

array([10, 20, 30, 40, 50, 60])